//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SheeToList.Resources.String {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppString() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SheeToList.Resources.String.AppString", typeof(AppString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter mot-clé.
        /// </summary>
        internal static string Category_add_title {
            get {
                return ResourceManager.GetString("Category_add_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Détails catégorie.
        /// </summary>
        internal static string category_detail_title {
            get {
                return ResourceManager.GetString("category_detail_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Éditer mot-clé.
        /// </summary>
        internal static string Category_edit_keyword {
            get {
                return ResourceManager.GetString("Category_edit_keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouveau mot-clé :.
        /// </summary>
        internal static string Category_edit_text {
            get {
                return ResourceManager.GetString("Category_edit_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot-clé :.
        /// </summary>
        internal static string Category_Keyword {
            get {
                return ResourceManager.GetString("Category_Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce mot-clé existe déjà.
        /// </summary>
        internal static string Category_popup_dublicate {
            get {
                return ResourceManager.GetString("Category_popup_dublicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Catégories.
        /// </summary>
        internal static string Category_title {
            get {
                return ResourceManager.GetString("Category_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OK.
        /// </summary>
        internal static string General_ok {
            get {
                return ResourceManager.GetString("General_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cachez.
        /// </summary>
        internal static string Main_cachez {
            get {
                return ResourceManager.GetString("Main_cachez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Catégorie.
        /// </summary>
        internal static string Main_category {
            get {
                return ResourceManager.GetString("Main_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recette.
        /// </summary>
        internal static string Main_recipe {
            get {
                return ResourceManager.GetString("Main_recipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Révélez tout.
        /// </summary>
        internal static string main_revelez {
            get {
                return ResourceManager.GetString("main_revelez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saisir un nom du produit.
        /// </summary>
        internal static string pick_popup_title {
            get {
                return ResourceManager.GetString("pick_popup_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Valider.
        /// </summary>
        internal static string pick_popup_valid {
            get {
                return ResourceManager.GetString("pick_popup_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter un ingrédient.
        /// </summary>
        internal static string popup_add {
            get {
                return ResourceManager.GetString("popup_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrez le nom....
        /// </summary>
        internal static string popup_addproduct_placeholder {
            get {
                return ResourceManager.GetString("popup_addproduct_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saisir un nom du produit.
        /// </summary>
        internal static string popup_addproduct_title {
            get {
                return ResourceManager.GetString("popup_addproduct_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annuler.
        /// </summary>
        internal static string popup_category_cancel {
            get {
                return ResourceManager.GetString("popup_category_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créer.
        /// </summary>
        internal static string popup_category_create {
            get {
                return ResourceManager.GetString("popup_category_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer la catégorie.
        /// </summary>
        internal static string popup_category_suppress {
            get {
                return ResourceManager.GetString("popup_category_suppress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom de la catégorie :.
        /// </summary>
        internal static string popup_category_text {
            get {
                return ResourceManager.GetString("popup_category_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouvelle catégorie.
        /// </summary>
        internal static string popup_category_title {
            get {
                return ResourceManager.GetString("popup_category_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cette catégorie existe déjà..
        /// </summary>
        internal static string popup_category_warn_title {
            get {
                return ResourceManager.GetString("popup_category_warn_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouveau nom:.
        /// </summary>
        internal static string popup_change_recipename_text {
            get {
                return ResourceManager.GetString("popup_change_recipename_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Changer le nom de la recette..
        /// </summary>
        internal static string popup_change_recipename_title {
            get {
                return ResourceManager.GetString("popup_change_recipename_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmer.
        /// </summary>
        internal static string popup_confirm {
            get {
                return ResourceManager.GetString("popup_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer .
        /// </summary>
        internal static string popup_del_confirm_1 {
            get {
                return ResourceManager.GetString("popup_del_confirm_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  ?.
        /// </summary>
        internal static string popup_del_confirm_2 {
            get {
                return ResourceManager.GetString("popup_del_confirm_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur.
        /// </summary>
        internal static string popup_error {
            get {
                return ResourceManager.GetString("popup_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer tous les produits ?.
        /// </summary>
        internal static string Popup_main_delete_all {
            get {
                return ResourceManager.GetString("Popup_main_delete_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cela supprimera toute la liste..
        /// </summary>
        internal static string Popup_main_import {
            get {
                return ResourceManager.GetString("Popup_main_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce produit est déjà dans la liste.   Sa quantité est augmenté d&apos;un..
        /// </summary>
        internal static string Popup_Main_Warn {
            get {
                return ResourceManager.GetString("Popup_Main_Warn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Non.
        /// </summary>
        internal static string popup_no {
            get {
                return ResourceManager.GetString("popup_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrer le nom de l&apos;objet à ajouté.
        /// </summary>
        internal static string Popup_Recipe_Add_Text {
            get {
                return ResourceManager.GetString("Popup_Recipe_Add_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrer le nom.
        /// </summary>
        internal static string Popup_Recipe_Add_Title {
            get {
                return ResourceManager.GetString("Popup_Recipe_Add_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cette recette est déjà dans la liste..
        /// </summary>
        internal static string Popup_Recipe_Warn {
            get {
                return ResourceManager.GetString("Popup_Recipe_Warn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cette ingrédient est déjà dans la liste..
        /// </summary>
        internal static string Popup_Recipe_Warn_Product {
            get {
                return ResourceManager.GetString("Popup_Recipe_Warn_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Renommer un ingrédient..
        /// </summary>
        internal static string popup_rename {
            get {
                return ResourceManager.GetString("popup_rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrer le nouveau nom..
        /// </summary>
        internal static string popup_rename_product {
            get {
                return ResourceManager.GetString("popup_rename_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cette ingredient est déjà dans la liste..
        /// </summary>
        internal static string popup_text {
            get {
                return ResourceManager.GetString("popup_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélectionner....
        /// </summary>
        internal static string popup_type_select_placeholder {
            get {
                return ResourceManager.GetString("popup_type_select_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélectionné : .
        /// </summary>
        internal static string popup_type_select_title {
            get {
                return ResourceManager.GetString("popup_type_select_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisis ou taper le produit à ajouter..
        /// </summary>
        internal static string popup_type_title {
            get {
                return ResourceManager.GetString("popup_type_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tape le produit à ajouter..
        /// </summary>
        internal static string Popup_typeOnly_Title {
            get {
                return ResourceManager.GetString("Popup_typeOnly_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Doublon.
        /// </summary>
        internal static string popup_warn_title {
            get {
                return ResourceManager.GetString("popup_warn_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Oui.
        /// </summary>
        internal static string popup_yes {
            get {
                return ResourceManager.GetString("popup_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ingrédients pour :.
        /// </summary>
        internal static string recipe_ingrediant {
            get {
                return ResourceManager.GetString("recipe_ingrediant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des recettes.
        /// </summary>
        internal static string Recipe_list_title {
            get {
                return ResourceManager.GetString("Recipe_list_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Test1.
        /// </summary>
        internal static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
    }
}
